/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 * OpenAPI spec version: 1.0.0
 */
import type { FindPetsByStatusStatusItem } from './findPetsByStatusStatusItem';

export type FindPetsByStatusParams = { status: FindPetsByStatusStatusItem[] };
