/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A tag for a pet
 */
export interface Tag {
  id?: number;
  name?: string;
}
